version: "3.9"
services:
  redis:
    image: redis:6.0.9-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data: